#!/usr/bin/env bash
set -e

echo "Setting up macOS environment..."

DOTFILES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
echo "Using dotfiles from: $DOTFILES_DIR"

###############################################################################
# HOMEBREW
###############################################################################

if ! command -v brew &> /dev/null; then
    echo "Installing Homebrew..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    if [[ $(uname -m) == 'arm64' ]]; then
        eval "$(/opt/homebrew/bin/brew shellenv)"
    else
        eval "$(/usr/local/bin/brew shellenv)"
    fi
fi

echo "Updating Homebrew..."
brew update

###############################################################################
# PACKAGES
###############################################################################

echo "Installing packages..."
brew install \
    zsh \
    neovim \
    git \
    gh \
    starship \
    eza \
    bat \
    ripgrep \
    fd \
    fzf \
    lazygit \
    delta \
    tig \
    zsh-autosuggestions \
    zsh-syntax-highlighting

###############################################################################
# FONTS
###############################################################################

echo "Installing Nerd Fonts..."
brew install --cask font-jetbrains-mono-nerd-font
brew install --cask font-recursive-code-nerd-font
brew install --cask font-roboto-mono-nerd-font

###############################################################################
# DEFAULT SHELL
###############################################################################

if [ "$SHELL" != "$(which zsh)" ]; then
    echo "Setting zsh as default shell..."
    chsh -s "$(which zsh)"
fi

###############################################################################
# DIRECTORIES
###############################################################################

mkdir -p ~/.config/delta
mkdir -p ~/.vim/autoload
mkdir -p ~/bin

###############################################################################
# SYMLINKS
###############################################################################

echo "Creating symlinks..."

# Git
ln -sf "$DOTFILES_DIR/git/gitconfig" ~/.gitconfig
ln -sf "$DOTFILES_DIR/git/gitconfig-macos" ~/.gitconfig-os
ln -sf "$DOTFILES_DIR/git/gitignore_global" ~/.gitignore_global
ln -sf "$DOTFILES_DIR/git/tigrc" ~/.tigrc
echo "  Linked git configs"

# Starship
ln -sf "$DOTFILES_DIR/config/starship.toml" ~/.config/starship.toml
echo "  Linked starship.toml"

# Delta themes
ln -sf "$DOTFILES_DIR/config/delta/themes.gitconfig" ~/.config/delta/themes.gitconfig
echo "  Linked delta themes"

# Vim
ln -sf "$DOTFILES_DIR/vim/vimrc" ~/.vimrc
ln -sf "$DOTFILES_DIR/vim/autoload/plug.vim" ~/.vim/autoload/plug.vim
echo "  Linked vim config"

# Shared bin scripts
if [ -d "$DOTFILES_DIR/bin/shared" ]; then
    for script in "$DOTFILES_DIR/bin/shared/"*; do
        if [ -f "$script" ]; then
            ln -sf "$script" ~/bin/"$(basename "$script")"
        fi
    done
    chmod +x ~/bin/* 2>/dev/null || true
    echo "  Linked shared bin scripts"
fi

# ZSH config loader
cat > ~/.zshrc << 'ZSHRC'
# Generated by setup-macos.sh — sources dotfiles configs
DOTFILES="$HOME/Developer/personal/dotfiles/personal"
[[ -f "$DOTFILES/shell/shared/zshrc" ]] && source "$DOTFILES/shell/shared/zshrc"
[[ -f "$DOTFILES/shell/macos/zshrc" ]] && source "$DOTFILES/shell/macos/zshrc"
ZSHRC
echo "  Created ~/.zshrc loader"

###############################################################################
# DONE
###############################################################################

echo ""
echo "macOS setup complete!"
echo ""
echo "Next steps:"
echo "  1. Close and reopen your terminal (or run 'exec zsh')"
echo "  2. Run 'gh auth login' to authenticate with GitHub"
echo "  3. Run ':PlugInstall' in vim to install plugins"
echo ""
